# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Verifpal < Formula
  desc "Cryptographic protocol analysis for students and engineers."
  homepage "https://verifpal.com"
  version "0.26.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://source.symbolic.software/verifpal/verifpal/-/releases/v0.26.0/downloads/verifpal_0.26.0_macos_amd64.zip"
      sha256 "c3ca4c8e6a37d402db0d80b74ddc6f68b858871a1bfd2edfbf009a47d767f35e"
    end
    if Hardware::CPU.arm?
      url "https://source.symbolic.software/verifpal/verifpal/-/releases/v0.26.0/downloads/verifpal_0.26.0_macos_arm64.zip"
      sha256 "72562ed305921c4037fdf8ddf4c0564d60162e1ae728bf9f5489424ce2fd0834"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://source.symbolic.software/verifpal/verifpal/-/releases/v0.26.0/downloads/verifpal_0.26.0_linux_amd64.zip"
      sha256 "009268e7baca810b9d181380ab1104181f349b52ae06585f69e33bf50622cc75"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://source.symbolic.software/verifpal/verifpal/-/releases/v0.26.0/downloads/verifpal_0.26.0_linux_arm64.zip"
      sha256 "c256f132e922c0de8a0e3c69e3bdcb7e582edb8fd9e6d426ad0cc358ce6b288f"
    end
  end

  def install
    bin.install "verifpal"
  end
end
