# This file was generated by GoReleaser. DO NOT EDIT.
class Verifpal < Formula
  desc "Cryptographic protocol analysis for students and engineers."
  homepage "https://verifpal.com"
  version "0.14.9"
  bottle :unneeded

  if OS.mac?
    url "https://source.symbolic.software/verifpal/verifpal/uploads/1179a2a0eabfd1842997a5bf6943bf4b/verifpal_0.14.9_macos_amd64.zip"
    sha256 "6e057a67469a0d34819f7d509ac010be40506623ec66b0bb6dfa8f6cbbea2a26"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://source.symbolic.software/verifpal/verifpal/uploads/b49d4aa13feeab0727f15ccf487a9304/verifpal_0.14.9_linux_amd64.zip"
      sha256 "99f75a5702407d90e9bbac2b64747775b73a6fd0f9ed25b95a9a9e8e8105ed26"
    end
  end

  def install
    bin.install "verifpal"
  end
end
