# This file was generated by GoReleaser. DO NOT EDIT.
cask "verifpal" do
  version "1.3.6"

  on_macos do
    on_arm do
      sha256 "6241d80f45c213b1fd1dbbc7628c0326b7582b4c96dd038a2707708dfae785c8"
      url "https://github.com/symbolicsoft/verifpal/releases/download/v#{version}/verifpal_#{version}_darwin_arm64.zip"
    end
    on_intel do
      sha256 "3bd15629500e69fd7ed6a554f9311c0f3c613519ff953e3e6661b35ccf518504"
      url "https://github.com/symbolicsoft/verifpal/releases/download/v#{version}/verifpal_#{version}_darwin_amd64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "60bae407affb539920ca1a9d96c0b4572465f575188f781e1db18ed17414d59a"
      url "https://github.com/symbolicsoft/verifpal/releases/download/v#{version}/verifpal_#{version}_linux_arm64.zip"
    end
    on_intel do
      sha256 "e1e470b26d45946ec36513ca8eb1b2840e7ba138f435324a983f473bc5d7f128"
      url "https://github.com/symbolicsoft/verifpal/releases/download/v#{version}/verifpal_#{version}_linux_amd64.zip"
    end
  end

  name "verifpal"
  desc "Cryptographic protocol analysis for real-world cryptographic protocols."
  homepage "https://verifpal.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "verifpal"
  manpage "man/verifpal-about.1"
  manpage "man/verifpal-completion.1"
  manpage "man/verifpal-diagram.1"
  manpage "man/verifpal-lsp.1"
  manpage "man/verifpal-pretty.1"
  manpage "man/verifpal-verify.1"
  manpage "man/verifpal.1"
  bash_completion "completions/verifpal.bash"
  fish_completion "completions/verifpal.fish"
  zsh_completion "completions/_verifpal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/verifpal"]
    end
  end

  # No zap stanza required
end
