# This file was generated by GoReleaser. DO NOT EDIT.
cask "verifpal" do
  version "1.4.3"

  on_macos do
    on_arm do
      sha256 "8a03d4ec7451f27825dc2246fc6370a32212fb0908fe262f264a8da984cd94c1"
      url "https://github.com/symbolicsoft/verifpal/releases/download/v#{version}/verifpal_#{version}_darwin_arm64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "f73a28b4d3aa88e986a00b5ed73690ae915f71c01a2037a1508dee0e35a80312"
      url "https://github.com/symbolicsoft/verifpal/releases/download/v#{version}/verifpal_#{version}_linux_arm64.zip"
    end
    on_intel do
      sha256 "23ec5e28ba0ef5a5aef3ede37bebb31c82c9fcf802212265f5bbc08770989ee6"
      url "https://github.com/symbolicsoft/verifpal/releases/download/v#{version}/verifpal_#{version}_linux_amd64.zip"
    end
  end

  name "verifpal"
  desc "Cryptographic protocol analysis for real-world cryptographic protocols."
  homepage "https://verifpal.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "verifpal"
  manpage "man/verifpal-about.1"
  manpage "man/verifpal-completion.1"
  manpage "man/verifpal-diagram.1"
  manpage "man/verifpal-lsp.1"
  manpage "man/verifpal-pretty.1"
  manpage "man/verifpal-verify.1"
  manpage "man/verifpal.1"
  bash_completion "completions/verifpal.bash"
  fish_completion "completions/verifpal.fish"
  zsh_completion "completions/_verifpal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/verifpal"]
    end
  end

  # No zap stanza required
end
