# This file was generated by GoReleaser. DO NOT EDIT.
cask "verifpal" do
  version "1.6.4"

  on_macos do
    on_arm do
      sha256 "5ac10eec95aa08a0e14a8d1d7b11367bd6e174b0b7a6ee52a93212d29a8e63fa"
      url "https://github.com/symbolicsoft/verifpal/releases/download/v#{version}/verifpal_#{version}_darwin_arm64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "324deff0b4adeb5a0137101a1df0efef0ab70944e56299d69d99ddb343bd65a2"
      url "https://github.com/symbolicsoft/verifpal/releases/download/v#{version}/verifpal_#{version}_linux_arm64.zip"
    end
    on_intel do
      sha256 "4cb81adf6d96ed9b637042e0b515b97c66baea0ade4d97218c7b70cb72357d1c"
      url "https://github.com/symbolicsoft/verifpal/releases/download/v#{version}/verifpal_#{version}_linux_amd64.zip"
    end
  end

  name "verifpal"
  desc "Cryptographic protocol analysis for real-world cryptographic protocols."
  homepage "https://verifpal.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "verifpal"
  manpage "man/verifpal-about.1"
  manpage "man/verifpal-completion.1"
  manpage "man/verifpal-diagram.1"
  manpage "man/verifpal-lsp.1"
  manpage "man/verifpal-pretty.1"
  manpage "man/verifpal-verify.1"
  manpage "man/verifpal.1"
  bash_completion "completions/verifpal.bash"
  fish_completion "completions/verifpal.fish"
  zsh_completion "completions/_verifpal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/verifpal"]
    end
  end

  # No zap stanza required
end
